#!/usr/bin/env python3

import sys


HELP_MESSAGE = '''
Usage: 
./gamenite <SUBCOMMAND> <ARGUMENTS...>
  - run a gamenite subcommand
./gamenite <SUBCOMMAND> help
  - print the usage and possible arguments for the given subcommand

Description:
A builder and manager for the other RecBox-Games repos related to the GameNite. 
This should be the only repo a developers should need to check out manually.

Subcommands:
* help: 
  - Show this help message.
* console: 
  - (not yet implemented) 
  - build rqn software on the console and manage version control 
* controlpad-tester: 
  - Build and manage the software package given to game developers for natively 
    testing controlpads with their games.
'''

def subcommand_console(args):
    print('Not yet implemented')

def subcommand_controlpad_tester(args):
    print('Not yet implemented')

def dispatch_subcommand(args):
    if len(args) == 0:
        print('You must provide a subcommand to this script. Try `gamenite help`')
    elif args[0] == 'help':
        print(HELP_MESSAGE)
    elif args[0] == 'console':
        subcommand_console(args[1:])
    elif args[0] == 'controlpad-tester':
        subcommand_controlpad_tester(args[1:])
    else:
        print('Subcommand not recognized. Try `gamenite help`')


if __name__ == '__main__':
    dispatch_subcommand(sys.argv[1:])

    
